

server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/around_cafe?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
    username: eddi
    password: eddi@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
