
server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/around_cafe?allowpublickeyretrieval=true&usessl=false&serverTimezone=Asia/Seoul
    username: eddi
    password: eddi@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect

  cache:
    type: redis

  redis:
    host: 127.0.0.1
    port: 6379

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

app:
  auth:
    jwt-secret: TEj9ZyurkG3LiRqjU9u9KrWrPDL5UDa/vL03rjMv5GqPXCYjOySIfOIqAXBkDzdU/rPALuyxGwj1z4tN4cayoA==
    jwt-expiration-ms: 60000 # 1000 * 60 * 1 = 1분(millisecond 기준)